### PR TITLE
Fix .rcomp executable path

### PR DESCRIPTION
**Pull request by dasmoose**
The old directory structure of marktab (from what I can tell) had an executable
in `bin`. `bin` no longer exists and the `cli` executable located at
`examples/cli` seems to now serve this purpose. This commit tells rcomp to test
against `examples/cli` instead of the old (it seems now nonexistant)
executable.

This allows the rcomp tests to run but none pass.

### CODE REVIEW

**Comment by cknadler** [comment]
Yeah, I more or less abandoned my RComp test suite a while ago in favor of check (located at `spec/check`). This actually gets the tests to run properly. They aren't passing because of an output bug that was introduced, causing tabs to output an extra whitespace line at the end of their body. This might be more complicated than it seems but I'll look into it.

**Comment by dasmoose** [comment]
Ah, ok. I'll see if I can look into that as well.

**Comment by cknadler** [comment]
If you are going to give that bug a shot, the output is being done in `src/mt_output.c`. The output handler is a complete mess though...

**Comment by dasmoose** [comment]
Ok. Thanks for the heads up. :sailboat:

**Comment by cknadler** [comment]
Come to think of it, since the only thing throwing the tests off is a single endline, this isn't really a problem. You could get the tests to pass by running:

``` bash
$ rcomp generate -O
```

This will overwrite the expected output of all of the current marktab tests. As long as you make sure that all of the tests are failing purely because of an extra newline at the end of the file, this should work just fine.

**Pull request merged**
